### ISSUE TITLE
[问题描述] 生成站点时报错了

### ISSUE THREAD

**Issue by istek** [EvanNotFound/hexo-theme-redefine#152]
**提交前检查单**
- [ * ] 已经尝试执行 `hexo clean`，问题仍然存在
- [ * ] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/docs/quick-start/update)
- [ * ] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/docs/quick-start/update#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)

**Bug 描述**
在生成网站时报错了，报错内容如下：
```

Github: https://github.com/EvanNotFound/hexo-theme-redefine
--
20:49:12.122 | current version is v2.1.4,latest version is v2.1.4
20:49:12.123 | ===================================================================
20:49:16.164 | INFO  Files loaded in 4.62 s
20:49:25.288 | ERROR Render HTML failed: firefox-for-the-first-time-reached-20-market-share/index.html
20:49:25.289 | SyntaxError: /vercel/path0/themes/redefine/layout/layout.ejs:3
20:49:25.289 | 1\| <!DOCTYPE html>
20:49:25.290 | 2\| <html lang="<%= config.language %>">
20:49:25.290 | >> 3\| <%- partial('_partials/head') %>
20:49:25.290 | 4\| <body>
20:49:25.290 | 5\| <%- body %>
20:49:25.290 | 6\| <%- partial('_partials/scripts') %>
20:49:25.290 |  
20:49:25.292 | /vercel/path0/themes/redefine/layout/_partials/head.ejs:50
20:49:25.292 | 48\|     <%- favicon_tag(url_for(theme.defaults.favicon)) %>
20:49:25.292 | 49\|     <!--- Page Info-->
20:49:25.293 | >> 50\|     <%
20:49:25.293 | 51\|     let title = page.title;
20:49:25.293 | 52\|     if (is_archive()) {
20:49:25.293 | 53\|         title = __('archive');
20:49:25.293 |  
20:49:25.293 | [sprintf] unexpected placeholder
20:49:25.293 | at sprintf_parse (/vercel/path0/node_modules/sprintf-js/src/sprintf.js:202:23)
20:49:25.294 | at sprintf (/vercel/path0/node_modules/sprintf-js/src/sprintf.js:26:31)
20:49:25.294 | at vsprintf (/vercel/path0/node_modules/sprintf-js/src/sprintf.js:30:24)
20:49:25.295 | at Object.__ (/vercel/path0/node_modules/hexo-i18n/lib/i18n.js:88:12)
20:49:25.295 | at eval ("/vercel/path0/themes/redefine/layout/_partials/head.ejs":101:17)
20:49:25.296 | at head (/vercel/path0/node_modules/ejs/lib/ejs.js:703:17)
20:49:25.296 | at _View._compiledSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:132:24)
20:49:25.296 | at _View.renderSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:59:25)
20:49:25.297 | at Object.partial (/vercel/path0/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
20:49:25.297 | at eval ("/vercel/path0/themes/redefine/layout/layout.ejs":15:17)
20:49:25.297 | at layout (/vercel/path0/node_modules/ejs/lib/ejs.js:703:17)
20:49:25.297 | at _View._compiled (/vercel/path0/node_modules/hexo/lib/theme/view.js:136:50)
20:49:25.297 | at _View.render (/vercel/path0/node_modules/hexo/lib/theme/view.js:39:17)
20:49:25.298 | at /vercel/path0/node_modules/hexo/lib/theme/view.js:51:25
20:49:25.298 | at tryCatcher (/vercel/path0/node_modules/bluebird/js/release/util.js:16:23)
20:49:25.298 | at Promise._settlePromiseFromHandler (/vercel/path0/node_modules/bluebird/js/release/promise.js:547:31)
20:49:25.298 | ERROR Render HTML failed: china-99-of-the-white-collar-is-going-bankrupt/index.html
20:49:25.299 | SyntaxError: /vercel/path0/themes/redefine/layout/layout.ejs:3
20:49:25.299 | 1\| <!DOCTYPE html>
20:49:25.299 | 2\| <html lang="<%= config.language %>">
20:49:25.299 | >> 3\| <%- partial('_partials/head') %>
20:49:25.299 | 4\| <body>
20:49:25.299 | 5\| <%- body %>
20:49:25.299 | 6\| <%- partial('_partials/scripts') %>
20:49:25.300 |  
20:49:25.300 | /vercel/path0/themes/redefine/layout/_partials/head.ejs:50
20:49:25.300 | 48\|     <%- favicon_tag(url_for(theme.defaults.favicon)) %>
20:49:25.300 | 49\|     <!--- Page Info-->
20:49:25.300 | >> 50\|     <%
20:49:25.300 | 51\|     let title = page.title;
20:49:25.301 | 52\|     if (is_archive()) {
20:49:25.301 | 53\|         title = __('archive');
20:49:25.301 |  
20:49:25.301 | [sprintf] unexpected placeholder
20:49:25.301 | at sprintf_parse (/vercel/path0/node_modules/sprintf-js/src/sprintf.js:202:23)
20:49:25.301 | at sprintf (/vercel/path0/node_modules/sprintf-js/src/sprintf.js:26:31)
20:49:25.302 | at vsprintf (/vercel/path0/node_modules/sprintf-js/src/sprintf.js:30:24)
20:49:25.302 | at Object.__ (/vercel/path0/node_modules/hexo-i18n/lib/i18n.js:88:12)
20:49:25.302 | at eval ("/vercel/path0/themes/redefine/layout/_partials/head.ejs":101:17)
20:49:25.302 | at head (/vercel/path0/node_modules/ejs/lib/ejs.js:703:17)
20:49:25.302 | at _View._compiledSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:132:24)
20:49:25.302 | at _View.renderSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:59:25)
20:49:25.302 | at Object.partial (/vercel/path0/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
20:49:25.302 | at eval ("/vercel/path0/themes/redefine/layout/layout.ejs":15:17)
20:49:25.302 | at layout (/vercel/path0/node_modules/ejs/lib/ejs.js:703:17)
20:49:25.302 | at _View._compiled (/vercel/path0/node_modules/hexo/lib/theme/view.js:136:50)
20:49:25.302 | at _View.render (/vercel/path0/node_modules/hexo/lib/theme/view.js:39:17)
20:49:25.303 | at /vercel/path0/node_modules/hexo/lib/theme/view.js:51:25
20:49:25.303 | at tryCatcher (/vercel/path0/node_modules/bluebird/js/release/util.js:16:23)
20:49:25.305 | at Promise._settlePromiseFromHandler (/vercel/path0/node_modules/bluebird/js/release/promise.js:547:31)
20:49:25.981 | ERROR
20:49:25.981 | SyntaxError: /vercel/path0/themes/redefine/layout/layout.ejs:3
20:49:25.982 | 1\| <!DOCTYPE html>
20:49:25.982 | 2\| <html lang="<%= config.language %>">
20:49:25.982 | >> 3\| <%- partial('_partials/head') %>
20:49:25.982 | 4\| <body>
20:49:25.982 | 5\| <%- body %>
20:49:25.982 | 6\| <%- partial('_partials/scripts') %>
20:49:25.982 |  
20:49:25.982 | /vercel/path0/themes/redefine/layout/_partials/head.ejs:50
20:49:25.982 | 48\|     <%- favicon_tag(url_for(theme.defaults.favicon)) %>
20:49:25.982 | 49\|     <!--- Page Info-->
20:49:25.982 | >> 50\|     <%
20:49:25.983 | 51\|     let title = page.title;
20:49:25.983 | 52\|     if (is_archive()) {
20:49:25.983 | 53\|         title = __('archive');
20:49:25.983 |  
20:49:25.983 | [sprintf] unexpected placeholder
20:49:25.983 | at sprintf_parse (/vercel/path0/node_modules/sprintf-js/src/sprintf.js:202:23)
20:49:25.983 | at sprintf (/vercel/path0/node_modules/sprintf-js/src/sprintf.js:26:31)
20:49:25.983 | at vsprintf (/vercel/path0/node_modules/sprintf-js/src/sprintf.js:30:24)
20:49:25.983 | at Object.__ (/vercel/path0/node_modules/hexo-i18n/lib/i18n.js:88:12)
20:49:25.983 | at eval ("/vercel/path0/themes/redefine/layout/_partials/head.ejs":101:17)
20:49:25.983 | at head (/vercel/path0/node_modules/ejs/lib/ejs.js:703:17)
20:49:25.984 | at _View._compiledSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:132:24)
20:49:25.984 | at _View.renderSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:59:25)
20:49:25.984 | at Object.partial (/vercel/path0/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
20:49:25.984 | at eval ("/vercel/path0/themes/redefine/layout/layout.ejs":15:17)
20:49:25.984 | at layout (/vercel/path0/node_modules/ejs/lib/ejs.js:703:17)
20:49:25.984 | at _View._compiled (/vercel/path0/node_modules/hexo/lib/theme/view.js:136:50)
20:49:25.984 | at _View.render (/vercel/path0/node_modules/hexo/lib/theme/view.js:39:17)
20:49:25.984 | at /vercel/path0/node_modules/hexo/lib/theme/view.js:51:25
20:49:25.984 | at tryCatcher (/vercel/path0/node_modules/bluebird/js/release/util.js:16:23)
20:49:25.984 | at Promise._settlePromiseFromHandler (/vercel/path0/node_modules/bluebird/js/release/promise.js:547:31)
20:49:25.985 | ERROR
20:49:25.985 | SyntaxError: /vercel/path0/themes/redefine/layout/layout.ejs:3
20:49:25.985 | 1\| <!DOCTYPE html>
20:49:25.985 | 2\| <html lang="<%= config.language %>">
20:49:25.985 | >> 3\| <%- partial('_partials/head') %>
20:49:25.985 | 4\| <body>
20:49:25.985 | 5\| <%- body %>
20:49:25.985 | 6\| <%- partial('_partials/scripts') %>
20:49:25.985 |  
20:49:25.985 | /vercel/path0/themes/redefine/layout/_partials/head.ejs:50
20:49:25.986 | 48\|     <%- favicon_tag(url_for(theme.defaults.favicon)) %>
20:49:25.986 | 49\|     <!--- Page Info-->
20:49:25.986 | >> 50\|     <%
20:49:25.986 | 51\|     let title = page.title;
20:49:25.986 | 52\|     if (is_archive()) {
20:49:25.986 | 53\|         title = __('archive');
20:49:25.986 |  
20:49:25.986 | [sprintf] unexpected placeholder
20:49:25.986 | at sprintf_parse (/vercel/path0/node_modules/sprintf-js/src/sprintf.js:202:23)
20:49:25.986 | at sprintf (/vercel/path0/node_modules/sprintf-js/src/sprintf.js:26:31)
20:49:25.987 | at vsprintf (/vercel/path0/node_modules/sprintf-js/src/sprintf.js:30:24)
20:49:25.987 | at Object.__ (/vercel/path0/node_modules/hexo-i18n/lib/i18n.js:88:12)
20:49:25.987 | at eval ("/vercel/path0/themes/redefine/layout/_partials/head.ejs":101:17)
20:49:25.987 | at head (/vercel/path0/node_modules/ejs/lib/ejs.js:703:17)
20:49:25.987 | at _View._compiledSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:132:24)
20:49:25.987 | at _View.renderSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:59:25)
20:49:25.987 | at Object.partial (/vercel/path0/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
20:49:25.988 | at eval ("/vercel/path0/themes/redefine/layout/layout.ejs":15:17)
20:49:25.988 | at layout (/vercel/path0/node_modules/ejs/lib/ejs.js:703:17)
20:49:25.989 | at _View._compiled (/vercel/path0/node_modules/hexo/lib/theme/view.js:136:50)
20:49:25.989 | at _View.render (/vercel/path0/node_modules/hexo/lib/theme/view.js:39:17)
20:49:25.989 | at /vercel/path0/node_modules/hexo/lib/theme/view.js:51:25
20:49:25.989 | at tryCatcher (/vercel/path0/node_modules/bluebird/js/release/util.js:16:23)
20:49:25.989 | at Promise._settlePromiseFromHandler (/vercel/path0/node_modules/bluebird/js/release/promise.js:547:31)
20:49:28.850 | INFO  Generated: firefox-for-the-first-time-reached-20-market-share/index.html
20:49:28.851 | INFO  Generated: china-99-of-the-white-collar-is-going-bankrupt/index.html
```

_config.redefine.yml
```
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# THEME REDEFINE CONFIGURATION FILE V2
# BY EVANNOTFOUND
# GITHUB: https://github.com/EvanNotFound/hexo-theme-redefine
# DOCUMENTATION: https://redefine-docs.ohevan.com
# DEMO: https://redefine.ohevan.com
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# BASIC INFORMATION >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
info:
  # Site title
  title: xxx
  # Author name
  author: 2ds
  # Site URL
  url: https://xxx.vercel.app/
# BASIC INFORMATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# IMAGE CONFIGURATION >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
defaults:
  # Favicon
  favicon: /images/redefine-favicon.svg
  # Site logo
  logo: 
  # Site avatar
  avatar: /images/redefine-avatar.svg
# IMAGE CONFIGURATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# COLORS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
colors:
  #Primary color
  primary: "#A31F34"
  # Secondary color (beta)
  secondary: 
# COLORS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# SITE CUSTOMIZATION >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
global:
  # Custom fonts
  fonts:
    # Chinese fonts
    chinese: 
      enable: false # Whether to enable custom chinese font
      family:  # Font family
      url:  # Font URL to CSS file
    # English fonts
    english: 
      enable: false # Whether to enable custom chinese font
      family:  # Font family
      url:  # Font URL to CSS file
  # Content max width
  content_max_width: 1000px
  # Sidebar width
  sidebar_width: 210px
  # Effects on mouse hover
  hover:
    shadow: true # shadow effect
    scale: false # scale effect
  # Scroll progress
  scroll_progress:
    bar: false # progress bar
    percentage: true # percentage
  # Website counter (powered by https://busuanzi.ibruce.info/)
  busuanzi_counter:
    enable: true # enable website counter or not
    site_pv: true # site page view
    site_uv: true # site unique visitor
    post_pv: true # post page view
  # Whether to enable PJAX
  pjax: true
  # Whether to enable open graph
  open_graph: true
  # Google Analytics
  google_analytics:
    enable: false # Whether to enable Google Analytics
    id:  # Google Analytics Measurement ID
# SITE CUSTOMIZATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end
    

# FONTAWESOME >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
fontawesome: # Pro v6.2.1
  # Thin version
  thin: false
  # Light version
  light: false
  # Duotone version
  duotone: false
  # Sharp Solid version
  sharp_solid: false
# FONTAWESOME <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# HOME BANNER >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
home_banner:
  # Whether to enable home banner
  enable: true
  # style of home banner
  style: static # static or fixed
  # Home banner image
  image: 
    light: /images/wallhaven-wqery6-light.webp # light mode
    dark: /images/wallhaven-wqery6-dark.webp # dark mode
  # Home banner title
  title: Theme Redefine
  # Home banner subtitle
  subtitle:
    text: [] # subtitle text, array
    hitokoto:  # 一言配置
      enable: false # Whether to enable hitokoto
      api: https://v1.hitokoto.cn # API URL, can add types, see https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0
    typing_speed: 100 # Typing speed (ms)
    backing_speed: 80 # Backing speed (ms)
    starting_delay: 500 # Start delay (ms)
    backing_delay: 1500 # Backing delay (ms)
    loop: true # Whether to loop
    smart_backspace: true # Whether to smart backspace
  # Color of home banner text
  text_color: 
    light: "#fff" # light mode
    dark: "#d1d1b6" # dark mode
  # Specific style of the text
  text_style: 
    # Title font size
    title_size: 2.8rem
    # Subtitle font size
    subtitle_size: 1.5rem
    # Line height between title and subtitle
    line_height: 1.2
  # Home banner custom font
  custom_font: 
    # Whether to enable custom font
    enable: false
    # Font family
    family: 
    # URL to font CSS file
    url:
  # Home banner social links
  social_links:
    # Whether to enable
    enable: false
    # Social links
    links:
      github:  # your GitHub URL
      instagram: # your Instagram URL
      zhihu:  # your ZhiHu URL
      twitter:  # your twitter URL
      email:  # your email
      # ...... # you can add more
# HOME BANNER <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# NAVIGATION BAR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
navbar:
  # Auto hide navbar
  auto_hide: false
  # Navbar background color
  color:
    left: "#f78736" #left side 
    right: "#367df7"  #right side
    transparency: 35 #percent (10-99)
  # Navbar links
  links:
    Home: 
      path: / 
      icon: fa-regular fa-house # can be empty
    # Archives: 
    #   path: /archives 
    #   icon: fa-regular fa-archive # can be empty
    # Status: 
    #   path: https://status.evanluo.top/
    #   icon: fa-regular fa-chart-bar
    # About: 
    #   icon: fa-regular fa-user
    #   submenus:
    #     Me: /about
    #     Github: https://github.com/EvanNotFound/hexo-theme-redefine
    #     Blog: https://ohevan.com
    #     Friends: /friends
    # Links: 
    #   icon: fa-regular fa-link
    #   submenus:
    #     Link1: /link1
    #     Link2: /link2
    #     Link3: /link3
    # ...... # you can add more
  # Navbar search (local search). Requires hexo-generator-searchdb (npm i hexo-generator-searchdb). See https://github.com/theme-next/hexo-generator-searchdb
  search:
    # Whether to enable
    enable: false
    # Preload search data when the page loads
    preload: true
# NAVIGATION BAR <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# HOME PAGE ARTICLE SETTINGS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
home:
  # Sidebar settings
  sidebar:
    enable: true # Whether to enable sidebar
    position: left # Sidebar position. left, right
    first_item: menu # First item in sidebar. menu, info
    announcement: # Announcement text
    links:
      # Archives: 
      #   path: /archives 
      #   icon: fa-regular fa-archive # can be empty
      # Tags: 
      #   path: /tags 
      #   icon: fa-regular fa-tags # can be empty
      # Categories: 
      #   path: /categories 
      #   icon: fa-regular fa-folder # can be empty
      # ...... # you can add more
  # Article date format
  article_date_format: auto # auto, relative, YYYY-MM-DD, YYYY-MM-DD HH:mm:ss etc.
  # Article categories visibility
  categories:
    enable: true  # Whether to enable
    limit: 3 # Max number of categories to display
  # Article tags visibility
  tags:
    enable: true  # Whether to enable
    limit: 3  # Max number of tags to display
# HOME PAGE ARTICLE SETTINGS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# ARTICLE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
articles:
  # Set the styles of the article
  style:
    font_size: 16px # Font size
    line_height: 1.5 # Line height
    image_border_radius: 14px # image border radius
    image_alignment: center # image alignment. left, center
    image_caption: false # Whether to display image caption
    link_icon: true # Whether to display link icon
  # Word count. Requires hexo-wordcount (npm install hexo-wordcount). See https://github.com/willin/hexo-wordcount
  word_count:
    enable: true # Whether to enable
    count: true # Whether to display word count
    min2read: true # Whether to display reading time
  # Author label
  author_label: 
    enable: true # Whether to enable
    auto: false # Whether to automatically add author label, e.g. Lv1, Lv2, Lv3...
    list: []
  # Code block settings
  code_block:
    copy: true # Whether to enable code block copy button
    style: mac # mac | simple
    font: # Custom font
      enable: false # Whether to enable
      family: # Font family
      url: # Font URL to CSS file
  # Table of contents settings
  toc:
    enable: true # Whether to enable TOC
    max_depth: 3 # TOC depth
    number: false # Whether to add number to TOC automatically
    expand: true # Whether to expand TOC
    init_open: true # Open toc by default
  # Whether to enable copyright notice
  copyright: true
  # Whether to enable lazyload for images
  lazyload: true
  # Article recommendation. Requires nodejieba (npm install nodejieba). Transplanted from hexo-theme-volantis.
  recommendation:
    # Whether to enable article recommendation
    enable: false
    # Article recommendation title
    title: 推荐阅读
    # Max number of articles to display
    limit: 3
    # Placeholder image
    placeholder: /images/wallhaven-wqery6-light.webp
    # Skip directory
    skip_dirs: []
# ARTICLE <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# COMMENT >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
comment:
  # Whether to enable comment
  enable: true
  # Comment system
  system: waline # waline, gitalk, twikoo
  # System configuration
  config:
    # Waline comment system. See https://waline.js.org/
    waline:
      serverUrl: https://example.example.com # Waline server URL. e.g. https://example.example.com
      lang: zh-CN # Waline language. e.g. zh-CN, en-US. See https://waline.js.org/guide/client/i18n.html
    # Gitalk comment system. See https://github.com/gitalk/gitalk
    gitalk:
      clientID: # GitHub Application Client ID
      clientSecret: # GitHub Application Client Secret
      repo: # GitHub repository
      owner: # GitHub repository owner
    # Twikoo comment system. See https://twikoo.js.org/
    twikoo:
      version: 1.6.10 # Twikoo version, do not modify if you dont know what it is
      server_url: # Twikoo server URL. e.g. https://example.example.com
      region: # Twikoo region. can be empty
# COMMENT <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# FOOTER >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
footer:
  # Show website running time
  runtime: true # show website running time or not
  # Icon in footer, write fontawesome icon code here
  icon: '<i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 0.5s; color: #f54545"></i>'
  # The start time of the website, format: YYYY/MM/DD HH:mm:ss
  start: 2022/8/17 11:45:14
  # Footer message
  customize:
  # ICP record number. See https://beian.miit.gov.cn/
  icp:
    enable: false # Whether to enable
    number: # ICP record number
    url: # ICP record url
# FOOTER <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# INJECT >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
inject:
  # Whether to enable inject
  enable: true
  # Inject custom head html code
  head: 
    -
    -
  # Inject custom footer html code
  footer:
    -
    -
# INJECT <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# PLUGINS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
plugins:
  # RSS feed. Requires hexo-generator-feed (npm i hexo-generator-feed). See https://github.com/hexojs/hexo-generator-feed
  feed:
    enable: true # Whether to enable
  # Aplayer. See https://github.com/DIYgod/APlayer
  aplayer:
    enable: false # Whether to enable
    type: fixed # fixed, mini
    audios:
      - name: # audio name
        artist: # audio artist
        url: # audio url
        cover: # audio cover url
      # - name: # audio name
      #   artist: # audio artist
      #   url: # audio url
      #   cover: # audio cover url
      # .... you can add more audios here
  # Mermaid JS. Requires hexo-filter-mermaid-diagrams (npm i hexo-filter-mermaid-diagrams). See https://mermaid.js.org/
  mermaid:
    enable: false # enable mermaid or not
    version: "9.3.0" # default v9.3.0
# PLUGINS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# PAGE TEMPLATES >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
page_templates:
  # Friend Links page column number
  friends_column: 2
  # Tags page style
  tags_style: blur # blur, cloud
# PAGE TEMPLATES <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# CDN >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
cdn:
  # Whether to enable CDN
  enable: true
  # CDN Provider
  provider: aliyun # aliyun, jsdelivr, unpkg, personal
# CDN <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end
```
**复现方法**
只要git push以后在生成站点的时候，就报错。使用hexo自带主题，没这个报错。

**Comment by EvanNotFound** [comment]
麻烦给我看一下  firefox-for-the-first-time-reached-20-market-share 这篇文章

**Comment by istek** [comment]
源文件如下：

```
---
title: 'Firefox首次达到20%市场份额'
date: 2008-11-05T23:22:02+00:00
author: Stanley
layout: post
permalink: /firefox-for-the-first-time-reached-20-market-share/
categories:
  - 我的世界
tags:
  - firefox
---
Mozilla的家伙们正在欢欣鼓舞，根据全球分析服务商Net Applications的一份报告，10月份前两周，Firefox在全球市场的占有率达到了20%。这是该世界第二流行的浏览器的市场份额新高。

Firefox安全、兼容性好、可扩展……而且不是微软的产品。这就是人们喜欢它的主要原因。你能想象读写网的读者有多少是用Firefox的吗？

作为Windows用户的非默认浏览器，Firefox可以作为一个标尺来衡量高端网络用户的总体数量。当然，有许多高端用户也在用IE。

![](https://i2.wp.com/www.readwriteweb.com/images/rwwbrowserstats.jpg?resize=220%2C310)

根据我们的统计，上个月我们有27%的读者是使用IE来访问读写网的。IE是我们的在我们的读者中第二流行的浏览器，仅次于Firefox的55%。10月份我们的读者总共使用过188种不同的浏览器。

浏览器领域的创新还在不断继续。今天Firefox刚刚增加了“Private Browsing”功能，这必然引起主流用户的极大兴趣。

恭喜Mozilla基金会和社区。一个通用Firefox的网络才是更好的。

```

**Comment by istek** [comment]
源文件如下：

```
---
title: 'Firefox首次达到20%市场份额'
date: 2008-11-05T23:22:02+00:00
author: Stanley
layout: post
permalink: /firefox-for-the-first-time-reached-20-market-share/
categories:
  - 我的世界
tags:
  - firefox
---
Mozilla的家伙们正在欢欣鼓舞，根据全球分析服务商Net Applications的一份报告，10月份前两周，Firefox在全球市场的占有率达到了20%。这是该世界第二流行的浏览器的市场份额新高。

Firefox安全、兼容性好、可扩展……而且不是微软的产品。这就是人们喜欢它的主要原因。你能想象读写网的读者有多少是用Firefox的吗？

作为Windows用户的非默认浏览器，Firefox可以作为一个标尺来衡量高端网络用户的总体数量。当然，有许多高端用户也在用IE。

![](https://i2.wp.com/www.readwriteweb.com/images/rwwbrowserstats.jpg?resize=220%2C310)

根据我们的统计，上个月我们有27%的读者是使用IE来访问读写网的。IE是我们的在我们的读者中第二流行的浏览器，仅次于Firefox的55%。10月份我们的读者总共使用过188种不同的浏览器。

浏览器领域的创新还在不断继续。今天Firefox刚刚增加了“Private Browsing”功能，这必然引起主流用户的极大兴趣。

恭喜Mozilla基金会和社区。一个通用Firefox的网络才是更好的。

```

**Comment by EvanNotFound** [comment]
把引号去掉试试看

**Comment by istek** [comment]
行，我这边试一下，谢谢。

**Comment by istek** [comment]
不行哦。还是一样的错误信息。

**Comment by EvanNotFound** [comment]
请把你的整个站点打包上传到 https://litterbox.catbox.moe/ 然后把链接复制给我。我帮你看看

**Comment by istek** [comment]
已经邮件给你了。谢谢。

**Comment by EvanNotFound** [comment]
已收到，正在帮你看

**Comment by EvanNotFound** [comment]
我找到原因了，文章标题不能有百分号 `%` ，有百分号就会报错。

这个不是主题问题，是渲染引擎的问题，因为 ejs 渲染模版中 `<% %>` 是标准语法，所以文章标题带百分号可能就误判了。解决办法只能是换成 `百分之 xx`

**Comment by istek** [comment]
哦。谢谢。这我查一下自己所有的文件title。

**Comment by EvanNotFound** [comment]
不需要一个一个查的，看哪个文章报错去改一下就行

**Comment by EvanNotFound** [comment]
我这边看下来是 

```
firefox-for-the-first-time-reached-20-market-share
china-99-of-the-white-collar-is-going-bankrupt
```

这两个文章报错，改一下应该就好了

**Comment by istek** [comment]
OK. 我这边修一下
