### ISSUE TITLE
[BUG] 文章推荐无法启用

### ISSUE THREAD

**Issue by shawn0915** [EvanNotFound/hexo-theme-redefine#246]
**提交前检查单**
- [ ] 已经尝试执行 `hexo clean`，问题仍然存在
- [ ] 已经更新到主题最新版本，详见 [官方文档 #更新](https://redefine-docs.ohevan.com/getting-started#%E6%9B%B4%E6%96%B0)
- [ ] 如果刚更新完主题出现此问题，已经确认同步了主题配置文件，[官方文档 #同步配置文件](https://redefine-docs.ohevan.com/getting-started#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE)

**Bug 描述**
清晰地描述，请提供
- hexo 根目录的网站配置文件 `_config.yml` 
- 主题配置文件 `_config.redefine.yml` 或 `_config.yml` 中有关的项目。如果有敏感信息请打码（替换一些字符

`npm install nodejieba@2.5.2` 无法安装，是否有其他办法？

https://github.com/yanyiwu/nodejieba/issues/225

**复现方法**
复现该 Bug 的步骤：

**预期结果**
该功能本来应该是怎么样的

**截图**
如果可以，请添加截图以帮助解释您的问题。

**电脑（请填写以下信息）：**
 - 操作系统：[例如 macOS, Windows]
 - 浏览器 [例如 Chrome, Safari]
 - 版本 [例如 108]

centos 7.9

**移动端（请填写以下信息）：**
 - 设备：[例如 iPhone 14]
 - 操作系统：[例如 iOS16.1]
 - 浏览器 [例如 Chrome, Safari]
 - 版本 [例如 108]

**其他**
如有其他内容，请提供

**Comment by anzai249** [comment]
试试cnpm吧，nodejieba装不上有很大概率是网络问题，另外建议把报错放出来

**Comment by shawn0915** [comment]
@anzai249 
```
[root@shawnyan homepage]# cnpm install nodejieba
⠴ [0/1] Installing concat-map@0.0.1
[npminstall:runscript:error] nodejieba@latest run install node-pre-gyp install --fallback-to-build error: Error: Command failed with exit code 1: node-pre-gyp install --fallback-to-build
    at makeError (/usr/local/lib/node_modules/cnpm/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/usr/local/lib/node_modules/cnpm/node_modules/execa/index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.exports.runScript (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/utils.js:261:12)
    at async runLifecycleScripts (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/lifecycle_scripts.js:66:7)
    at async _install (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/install_package.js:321:5)
    at async install (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/install_package.js:23:12)
    at async _installOne (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/local_install.js:215:15)
    at async mapper (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/local_install.js:140:5) {
  shortMessage: 'Command failed with exit code 1: node-pre-gyp install --fallback-to-build',
  command: 'node-pre-gyp install --fallback-to-build',
  escapedCommand: 'node-pre-gyp install --fallback-to-build',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
✖ Install fail! Error: run install error, please remove node_modules before retry!
Command failed with exit code 1: node-pre-gyp install --fallback-to-build
Error: Command failed with exit code 1: node-pre-gyp install --fallback-to-build
    at makeError (/usr/local/lib/node_modules/cnpm/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/usr/local/lib/node_modules/cnpm/node_modules/execa/index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.exports.runScript (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/utils.js:261:12)
    at async runLifecycleScripts (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/lifecycle_scripts.js:66:7)
    at async _install (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/install_package.js:321:5)
    at async install (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/install_package.js:23:12)
    at async _installOne (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/local_install.js:215:15)
    at async mapper (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/local_install.js:140:5)
npminstall version: 7.11.0
npminstall argv: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/root/.cnpmrc --disturl=https://cdn.npmmirror.com/binaries/node --registry=https://registry.npmmirror.com nodejieba

```

**Comment by shawn0915** [comment]
upgrade OS and resolved.
