### ISSUE TITLE
[Question]新版本部署后网站一片空白

### ISSUE THREAD

**Issue by 66622a** [EvanNotFound/hexo-theme-redefine#88]
**提交前检查单**
- [x] 已经尝试执行 `hexo clean`，问题仍然存在

**Bug 描述**
清晰地描述，请提供
- hexo 根目录的网站配置文件 `_config.yml` 
- 主题配置文件 `_config.redefine.yml` 或 `_config.yml` 中有关的项目。如果有敏感信息请打码（替换一些字符

只有升级后才会出现该问题，升级前原版本为1.1.12，升级1.1.13以上版本以后网站的源代码一片空白
nodejs版本为16

```
# ---------------------------------------------------------------------------------------
#  Your basic info
# ---------------------------------------------------------------------------------------
base_info:
  title: # Site title
  author:  # Author name
  url: # Site url
  # Logo image (You can use local image, image external link or don’t fill)
  logo_img: # logo image on the left of the navigation bar

# ---------------------------------------------------------------------------------------
# Theme style settings
# ---------------------------------------------------------------------------------------
style:
  # Theme primary color
  primary_color: "#005080"

  # Avatar (You can use local image or image external link)
  avatar: /images/logo.jpg # avatar of the author

  # Favicon (You can use local image or image external link)
  favicon: /images/logo1.png # favicon of the site

  # Article image align position
  article_img_align: center # value: left | center

  # Right side width
  right_side_width: 210px #sidebar width, for toc

  # Content area max width
  content_max_width: 1000px #content max width, for article

  #navigation bar background color (from left to right)
  nav_color: 
    left: "#f78736" #left side 
    right: "#367df7"  #right side
    transparency: 35 #percent (10-99)

  # Mouse hover
  hover:
    shadow: true # shadow effect when the mouse hover
    scale: false # scale effect when the mouse hover

  # First screen
  first_screen:
    enable: true
    background_image:
      light: /images/light-01.jpg # background image of the first screen, use relative path or external link (if your website is in subdirectory, use external link)
      dark: /images/99230581_p0_zip.png # background image of the first screen, use relative path or external link (if your website is in subdirectory, use external link)
    title_color:
      light: "#fff" # first screen title color (light mode)
      dark: "#d1d1b6" # first screen title color (dark mode)
    description:  # the title in the middle of the first screen. HTML supported (e.g. svg html code of your logo)

  # Scroll style settings
  scroll:
    progress_bar: # reading progress bar
      enable: true 
    percent: # reading progress percent
      enable: true

# ---------------------------------------------------------------------------------------
# Social contact link
# ---------------------------------------------------------------------------------------
social_contact: # social contact icons in the first screen, you can add more by using fontawesome icon names
  enable: true
  links:
    github:  # your GitHub URL
    instagram: # your Instagram URL
    zhihu:  # your ZhiHu URL
    twitter:  # your twitter URL
    email:  # your email
    # ...... # you can add more

# ---------------------------------------------------------------------------------------
# Navigation menu
# ---------------------------------------------------------------------------------------
menu: #you can customize, i18n files are in the theme's languages folder. fa-regular recommended
  Home: 
    path: / 
    icon: fa-regular fa-house # can be empty
  Archives: 
    path: /archives 
    icon: fa-regular fa-archive # can be empty
  Links: 
    path: /links
    icon: fa-regular fa-link
  # ......
  # Status: 
  #   path: https://status.evanluo.top/
  #   icon: fa-regular fa-chart-bar
  # About: 
  #   icon: fa-regular fa-user
  #   submenus:
  #     Me: /about
  #     Github: https://github.com/EvanNotFound/hexo-theme-redefine
  #     Blog: https://www.evanluo.top
  #     Friends: /friends
  # Links: 
  #   icon: fa-regular fa-link
  #   submenus:
  #     Link1: /link1
  #     Link2: /link2
  #     Link3: /link3

  # ...... # you can add more



# ---------------------------------------------------------------------------------------
# Home page article block display settings
# ---------------------------------------------------------------------------------------
home_article:
  category:
    enable: true # show category in home page article block
    limit: 3 # max number of categories shown in home page article block
  tag:
    enable: true # show tags in home page article block
    limit: 3 # max number of tags shown in home page article block

# ---------------------------------------------------------------------------------------
# Post page Settings
# ---------------------------------------------------------------------------------------
post:
  # Post word count
  # Dependencies: hexo-wordcount (npm install hexo-wordcount)
  # See: https://github.com/willin/hexo-wordcount
  word_count:
    enable: true
    wordcount: true # word count, one article
    min2read: true # time to read, one article

  # Author label
  author_label:
    enable: true
    auto: false # if true, show Lv1, Lv2, Lv3... , If false, show custom label
    # label array item can be one or more
    custom_label_list: ["Lv6"]

# ---------------------------------------------------------------------------------------
# Code copy
# ---------------------------------------------------------------------------------------
code_block:
  copy: true # enable code copy button
  style: mac # mac | simple

# ---------------------------------------------------------------------------------------
# Table of Contents in the Sidebar
# ---------------------------------------------------------------------------------------
toc:
  enable: true

  # Automatically add list number to toc.
  number: false

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: true

  # If true, open TOC every time when you enter the article page
  init_open: true

# ---------------------------------------------------------------------------------------
# Post copyright info
# ---------------------------------------------------------------------------------------
copyright_info:
  enable: true

# ---------------------------------------------------------------------------------------
# Website count
# ---------------------------------------------------------------------------------------
website_count:
  # busuanzi
  # See: http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: true
    site_uv: true
    site_pv: true
    page_pv: true

# ---------------------------------------------------------------------------------------
# Local Search
# Dependencies: hexo-generator-searchdb
# See: https://github.com/theme-next/hexo-generator-searchdb
# ---------------------------------------------------------------------------------------
local_search:
  enable: true
  preload: true # Preload the search data when the page loads

# ---------------------------------------------------------------------------------------
# Comment plugin
# ---------------------------------------------------------------------------------------
comment:
  enable: true
  use: waline # values: waline | gitalk | twikoo

  # Waline
  # See: https://waline.js.org/guide/get-started.html
  waline:
    serverUrl: # Waline server url(vercel) example: https://example.example.com
    lang: zh-CN # Waline language, default: zh-CN. See: https://waline.js.org/guide/client/i18n.html
  
  # Gitalk
  # See: https://github.com/gitalk/gitalk
  gitalk:
    github_id: # GitHub repo owner
    repository:  # Repository name to store issues
    client_id: # GitHub Application Client ID
    client_secret: # GitHub Application Client Secret

  # Twikoo
  # See: https://github.com/imaegoo/twikoo
  twikoo:
    visitor: true
    env_id: # Vercel or Tencent Cloud Function environment ID
    region: # environment region. If select Guangzhou, fill in "ap-guangzhou". (optional)

# ---------------------------------------------------------------------------------------
# Friend Links page
# ---------------------------------------------------------------------------------------
friend_links:
  columns: 2 # number of columns. 2 or 3

# ---------------------------------------------------------------------------------------
# RSS
# Dependencies: hexo-generator-feed
# See: https://github.com/hexojs/hexo-generator-feed
# ---------------------------------------------------------------------------------------
rss:
  enable: false

# ---------------------------------------------------------------------------------------
# Lazyload image
# ---------------------------------------------------------------------------------------
lazyload:
  enable: true

# ---------------------------------------------------------------------------------------
# CDN
# ---------------------------------------------------------------------------------------
cdn:
  enable: true

# ---------------------------------------------------------------------------------------
# PJAX
# ---------------------------------------------------------------------------------------
pjax:
  enable: true

# ---------------------------------------------------------------------------------------
# Fontawesome
# ---------------------------------------------------------------------------------------
fontawesome: # select fontawesome versions you want to use, in order to reduce the loading time, select as few as possible
  thin: false # use fontawesome thin version or not
  light: false # use fontawesome light version or not
  duotone: false # use fontawesome duotone version or not

# ---------------------------------------------------------------------------------------
# Footer settings
# ---------------------------------------------------------------------------------------
footer:
  runtime: true # show website running time or not
  start_time: 2022/10/1 11:00:00 # the starting time of your website, format: yyyy/mm/dd hh:mm:ss
  customize:  # customize footer message, can be html code
  icp: # ICP record number of your website, Can be null

# ---------------------------------------------------------------------------------------
# Redefine Theme version (Please dont modify it)
# Please go to github to update the latest version frequently
# ---------------------------------------------------------------------------------------
version: 1.1.2

# Search
## See: https://github.com/theme-next/hexo-generator-searchdb
search:
  path: search.json
  field: post
  content: true
  format: striptags

recommended_article: # 文章推荐，需要 npm install nodejieba
  enable: false
  title: 推荐阅读
  icon: fa-solid fa-bookmark
  max_count: 3
  placeholder_img: https://evan.beee.top/img/wallhaven-wqery6-light.webp
  # 不展示文章推荐：
  # front-matter 使用 skip_recommended_article: true 关闭
  # 不在以下文件夹文章中展示文章推荐 根目录是source/
  #skip_dirs:
  #  - wiki/
```

**复现方法**
复现该 Bug 的步骤：
升级到1.1.2以上的版本

**预期结果**
该功能本来应该是怎么样的
站点可以正常显示

**截图**
如果可以，请添加截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/71886213/222892353-f5e562c8-e5ff-427e-a4df-0ea4940ba670.png)
元素为空

**电脑（请填写以下信息）：**
 - 操作系统：[例如 macOS, Windows]
 - 浏览器 [例如 Chrome, Safari]
 - 版本 [例如 108]
- 操作系统：Windows
 - 浏览器 ：Chrome
 - 版本：110
 - 
**移动端（请填写以下信息）：**
 - 设备：[例如 iPhone 14]
 - 操作系统：[例如 iOS16.1]
 - 浏览器 [例如 Chrome, Safari]
 - 版本 [例如 108]

**其他**
如有其他内容，请提供

构建时出现了特别多例如这样的错误，如：
```
<html>
<body>
<!--StartFragment-->

ERROR TypeError: /vercel/path0/node_modules/hexo-theme-redefine/layout/page.ejs:54
--
17:41:10.290 | 52\|
17:41:10.290 | 53\|         <div class="page-main-content-bottom">
17:41:10.290 | >> 54\|             <%- partial('_partials/footer') %>
17:41:10.290 | 55\|         </div>
17:41:10.290 | 56\|     </div>
17:41:10.290 | 57\|
17:41:10.290 |  
17:41:10.290 | /vercel/path0/node_modules/hexo-theme-redefine/layout/_partials/footer.ejs:31
17:41:10.291 | 29\|             <%# 保留主题信息是对作者的尊重，感谢！ %><span class="theme-version-container"><%- __('theme') %>&nbsp;<a class="theme-version" target="_blank" href="https://github.com/EvanNotFound/hexo-theme-redefine">Redefine v<%= theme.version %></a><%# 保留主题信息是对作者的尊重，感谢！ %>
17:41:10.291 | 30\|         </div>
17:41:10.291 | >> 31\|         <% if (theme.footer.icp.enable && theme.footer.icp.hasOwnProperty('number')) { %>
17:41:10.291 | 32\|             <div class="icp-info info-item"><a target="_blank" rel="nofollow" href="
17:41:10.291 | 33\|                 <% if (theme.footer.icp.hasOwnProperty('url') && theme.footer.icp.url) { %>
17:41:10.291 | 34\|                     <%= theme.footer.icp.url %>
17:41:10.291 |  
17:41:10.291 | Cannot read property 'enable' of null
17:41:10.291 | at eval (eval at compile (/vercel/path0/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:673:12), <anonymous>:64:29)
17:41:10.292 | at footer (/vercel/path0/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:703:17)
17:41:10.292 | at _View._compiledSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:132:24)
17:41:10.292 | at _View.renderSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:59:25)
17:41:10.292 | at Object.partial (/vercel/path0/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
17:41:10.292 | at eval (eval at compile (/vercel/path0/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:673:12), <anonymous>:82:17)
17:41:10.292 | at page (/vercel/path0/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:703:17)
17:41:10.293 | at _View._compiled (/vercel/path0/node_modules/hexo/lib/theme/view.js:136:50)
17:41:10.293 | at _View.render (/vercel/path0/node_modules/hexo/lib/theme/view.js:39:17)
17:41:10.293 | at /vercel/path0/node_modules/hexo/lib/hexo/index.js:64:21
17:41:10.293 | at tryCatcher (/vercel/path0/node_modules/bluebird/js/release/util.js:16:23)
17:41:10.293 | at /vercel/path0/node_modules/bluebird/js/release/method.js:15:34
17:41:10.293 | at RouteStream._read (/vercel/path0/node_modules/hexo/lib/hexo/router.js:47:5)
17:41:10.293 | at RouteStream.Readable.read (internal/streams/readable.js:465:10)
17:41:10.293 | at resume_ (internal/streams/readable.js:962:12)
17:41:10.294 | at processTicksAndRejections (internal/process/task_queues.js:82:21) {
17:41:10.294 | path: '/vercel/path0/node_modules/hexo-theme-redefine/layout/page.ejs'
17:41:10.294 | }

<!--EndFragment-->
</body>
</html>

<html>
<body>
<!--StartFragment-->

ERROR TypeError: /vercel/path0/node_modules/hexo-theme-redefine/layout/archive.ejs:1
--
17:41:10.304 | >> 1\| <%- partial('page') %>
17:41:10.305 |  
17:41:10.305 | /vercel/path0/node_modules/hexo-theme-redefine/layout/page.ejs:54
17:41:10.305 | 52\|
17:41:10.305 | 53\|         <div class="page-main-content-bottom">
17:41:10.305 | >> 54\|             <%- partial('_partials/footer') %>
17:41:10.305 | 55\|         </div>
17:41:10.305 | 56\|     </div>
17:41:10.305 | 57\|
17:41:10.305 |  
17:41:10.306 | /vercel/path0/node_modules/hexo-theme-redefine/layout/_partials/footer.ejs:31
17:41:10.306 | 29\|             <%# 保留主题信息是对作者的尊重，感谢！ %><span class="theme-version-container"><%- __('theme') %>&nbsp;<a class="theme-version" target="_blank" href="https://github.com/EvanNotFound/hexo-theme-redefine">Redefine v<%= theme.version %></a><%# 保留主题信息是对作者的尊重，感谢！ %>
17:41:10.306 | 30\|         </div>
17:41:10.306 | >> 31\|         <% if (theme.footer.icp.enable && theme.footer.icp.hasOwnProperty('number')) { %>
17:41:10.306 | 32\|             <div class="icp-info info-item"><a target="_blank" rel="nofollow" href="
17:41:10.307 | 33\|                 <% if (theme.footer.icp.hasOwnProperty('url') && theme.footer.icp.url) { %>
17:41:10.307 | 34\|                     <%= theme.footer.icp.url %>
17:41:10.307 |  
17:41:10.307 | Cannot read property 'enable' of null
17:41:10.307 | at eval (eval at compile (/vercel/path0/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:673:12), <anonymous>:64:29)
17:41:10.307 | at footer (/vercel/path0/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:703:17)
17:41:10.307 | at _View._compiledSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:132:24)
17:41:10.307 | at _View.renderSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:59:25)
17:41:10.308 | at Object.partial (/vercel/path0/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
17:41:10.308 | at eval (eval at compile (/vercel/path0/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:673:12), <anonymous>:82:17)
17:41:10.308 | at page (/vercel/path0/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:703:17)
17:41:10.308 | at _View._compiledSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:132:24)
17:41:10.308 | at _View.renderSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:59:25)
17:41:10.308 | at Object.partial (/vercel/path0/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
17:41:10.308 | at eval (eval at compile (/vercel/path0/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:673:12), <anonymous>:10:17)
17:41:10.309 | at archive (/vercel/path0/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:703:17)
17:41:10.309 | at _View._compiled (/vercel/path0/node_modules/hexo/lib/theme/view.js:136:50)
17:41:10.309 | at _View.render (/vercel/path0/node_modules/hexo/lib/theme/view.js:39:17)
17:41:10.309 | at /vercel/path0/node_modules/hexo/lib/hexo/index.js:64:21
17:41:10.309 | at tryCatcher (/vercel/path0/node_modules/bluebird/js/release/util.js:16:23) {
17:41:10.309 | path: '/vercel/path0/node_modules/hexo-theme-redefine/layout/archive.ejs'
17:41:10.309 | }

<!--EndFragment-->
</body>
</html>

<html>
<body>
<!--StartFragment-->

ERROR TypeError: /vercel/path0/node_modules/hexo-theme-redefine/layout/404.ejs:1
--
17:45:56.419 | >> 1\| <%- partial('page') %>
17:45:56.419 |  
17:45:56.419 | /vercel/path0/node_modules/hexo-theme-redefine/layout/page.ejs:54
17:45:56.419 | 52\|
17:45:56.419 | 53\|         <div class="page-main-content-bottom">
17:45:56.419 | >> 54\|             <%- partial('_partials/footer') %>
17:45:56.419 | 55\|         </div>
17:45:56.419 | 56\|     </div>
17:45:56.419 | 57\|
17:45:56.419 |  
17:45:56.420 | /vercel/path0/node_modules/hexo-theme-redefine/layout/_partials/footer.ejs:31
17:45:56.420 | 29\|             <%# 保留主题信息是对作者的尊重，感谢！ %><span class="theme-version-container"><%- __('theme') %>&nbsp;<a class="theme-version" target="_blank" href="https://github.com/EvanNotFound/hexo-theme-redefine">Redefine v<%= theme.version %></a><%# 保留主题信息是对作者的尊重，感谢！ %>
17:45:56.420 | 30\|         </div>
17:45:56.420 | >> 31\|         <% if (theme.footer.icp.enable && theme.footer.icp.hasOwnProperty('number')) { %>
17:45:56.420 | 32\|             <div class="icp-info info-item"><a target="_blank" rel="nofollow" href="
17:45:56.420 | 33\|                 <% if (theme.footer.icp.hasOwnProperty('url') && theme.footer.icp.url) { %>
17:45:56.420 | 34\|                     <%= theme.footer.icp.url %>
17:45:56.420 |  
17:45:56.420 | Cannot read properties of null (reading 'enable')
17:45:56.420 | at eval ("/vercel/path0/node_modules/hexo-theme-redefine/layout/_partials/footer.ejs":64:29)
17:45:56.420 | at footer (/vercel/path0/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:703:17)
17:45:56.420 | at _View._compiledSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:132:24)
17:45:56.421 | at _View.renderSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:59:25)
17:45:56.421 | at Object.partial (/vercel/path0/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
17:45:56.421 | at eval ("/vercel/path0/node_modules/hexo-theme-redefine/layout/page.ejs":82:17)
17:45:56.421 | at page (/vercel/path0/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:703:17)
17:45:56.421 | at _View._compiledSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:132:24)
17:45:56.421 | at _View.renderSync (/vercel/path0/node_modules/hexo/lib/theme/view.js:59:25)
17:45:56.421 | at Object.partial (/vercel/path0/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
17:45:56.421 | at eval ("/vercel/path0/node_modules/hexo-theme-redefine/layout/404.ejs":10:17)
17:45:56.421 | at 404 (/vercel/path0/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:703:17)
17:45:56.421 | at _View._compiled (/vercel/path0/node_modules/hexo/lib/theme/view.js:136:50)
17:45:56.421 | at _View.render (/vercel/path0/node_modules/hexo/lib/theme/view.js:39:17)
17:45:56.421 | at /vercel/path0/node_modules/hexo/lib/hexo/index.js:64:21
17:45:56.421 | at tryCatcher (/vercel/path0/node_modules/bluebird/js/release/util.js:16:23) {
17:45:56.422 | path: '/vercel/path0/node_modules/hexo-theme-redefine/layout/404.ejs'
17:45:56.422 | }

<!--EndFragment-->
</body>
</html>
```
等等

**Comment by EvanNotFound** [comment]
[迁移配置文件](https://redefine-docs.ohevan.com/docs/quick-start/update#%E8%BF%81%E7%A7%BB%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)，因为在 `v1.1.3` 加入了页脚 icp 备案号的链接。

在你的 `_config.redefine.yml` 里面，`footer` 部分

把
```yaml
# ---------------------------------------------------------------------------------------
# Footer settings
# ---------------------------------------------------------------------------------------
footer:
  runtime: true # show website running time or not
  start_time: 2022/10/1 11:00:00 # the starting time of your website, format: yyyy/mm/dd hh:mm:ss
  customize:  # customize footer message, can be html code
  icp: # ICP record number of your website, Can be null
```
改为
https://github.com/EvanNotFound/hexo-theme-redefine/blob/faad133bf57f0b05a65fedfc2f922ff266ceb560/_config.yml#L278-L289
